version: '3.9'

services:
  msu-mongodb:
    image: mongo
    restart: unless-stopped
    container_name: cardcheck-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb-net

  cardcheck:
    env_file:
      - .env
    build: .
    container_name: cardcheck
    depends_on:
      - cardcheck-mongodb
    restart: unless-stopped
    ports:
      - ${APP_PORT}
    networks:
      - mongodb-net
      - localnet 
    volumes:
      - mongo-data

volumes:
  mongo-data:

networks:
  mongodb-net:
    external: true
    driver: bridge
    name: mongodb-net

  localnet:
    external: true
    name: localnet
