version: "3"

dotenv: ['.env']

tasks:
  run:
    env:
      DB_HOST: localhost
    cmds:
      - go run cmd/main.go

  test:
    cmds:
      - go test ./...

  swaginit:
    cmds:
      - swag init --outputTypes go,yaml -g cmd/main.go internal/model

  run-container:
    cmds:
      - git stash
      - git pull
      - docker compose build
      - docker compose down
      - docker compose up -d
