basePath: /
definitions:
  domain.Card:
    properties:
      card_number:
        example: "5167803252097675"
        type: string
      expiration_month:
        example: "12"
        type: string
      expiration_year:
        example: "2028"
        type: string
    required:
    - card_number
    - expiration_month
    - expiration_year
    type: object
  domain.Error:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/domain.ErrorCode'
        example: "001"
      message:
        example: error message
        type: string
    type: object
  domain.ErrorCode:
    enum:
    - "001"
    - "002"
    type: string
    x-enum-varnames:
    - InvalidCardNumber
    - InvalidExpirationDate
  domain.Response:
    properties:
      error:
        $ref: '#/definitions/domain.Error'
      valid:
        example: true
        type: boolean
    type: object
  domain.ResponseMessage:
    properties:
      message:
        example: response message
        type: string
    type: object
host: localhost:3000
info:
  contact:
    name: Mark Raiter
  description: This is an API for validating credit cards.
  title: Cardcheck API
  version: "1.0"
paths:
  /check:
    post:
      consumes:
      - application/json
      description: Validate card - check if card number is valid and expiration date
        is not in the past
      parameters:
      - description: Card to validate
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/domain.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ResponseMessage'
      summary: Validate card
      tags:
      - check
schemes:
- http
swagger: "2.0"
